[build]
publish = "public"
command = "make build"
functions = "functions"

[context.production.environment]
HUGO_VERSION = "0.60.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_IMPORT_PATH = "github.com/sigma/test.yrh.dev"

[[redirects]]
  from = "/:repo/*"
  to = "/.netlify/functions/vanity_v3"
  status = 200
  force = true
  query = {go-get = "1"}
  headers = {X-Repo = "gh-vanity"}
